### ISSUE TITLE
redis pipe

### ISSUE THREAD

**Issue by molibei** [swoole/php-connect-pool#2]
目前的版本貌似不支持pipe,希望完善,谢谢

**Comment by GXhua** [comment]
$redis = new redis_connect_pool();
  $redis->connect("127.0.0.1");
   $redis->select(1);
  $redis->multi(Redis::PIPELINE);
   $redis->incr("key");
   $redis->incr("key");
   $redis->incr("key");
   $redis->incr("key");
   $redis->exec();
   $redis->release();

我试了一下  是可以的哈，记得在exec之后再release连接到池子里面

**Comment by molibei** [comment]
额,今天又测了下，问题出在`select`上,在建立redis链接的时候，如果使用默认数据库,就会有问题
