### ISSUE TITLE
请问使用connect-pool后，还需要db close的操作吗？

### ISSUE THREAD

**Issue by xxluan** [swoole/php-connect-pool#3]
db连接改为 $db = new pdo_connect_pool(xxxx);
执行完sql后，执行$db->release()
还需要像以前那样再执行$db->close吗？

**Comment by molibei** [comment]
不用再close

**Comment by GXhua** [comment]
pdo是没有close的方法的把，redis的话千万别close  ，会把池子里面的连接也close掉
